######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 23 14:02:53 2015
######################################################################

TEMPLATE = app
TARGET = img-sub
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QMAKE_CXXFLAGS = -std=c++11
OBJECTS_DIR = .obj
