######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 23 14:02:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
